# Generated by Django 4.0.3 on 2022-03-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_alter_product_image_alter_product_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='promotional_marketing_price',
            field=models.FloatField(blank=True, null=True, verbose_name='Preço Promocional'),
        ),
    ]
