# Generated by Django 4.0.3 on 2022-03-23 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_alter_product_promotional_marketing_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type_product',
            new_name='variations',
        ),
    ]
