# Generated by Django 4.0.3 on 2022-04-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_alter_purchaseitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='quantity_items',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
